"""Add likes_count and fix models

Revision ID: 5cc9c70b6793
Revises: 
Create Date: 2026-03-07 16:25:06.449105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc9c70b6793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('join_permission', sa.String(length=20), nullable=True))

    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('target_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('target_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('diary', schema=None) as batch_op:
        batch_op.drop_column('join_permission')
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
